// Package item provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package item

// Item defines model for Item.
type Item struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}
