// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)
